### ISSUE TITLE
Sound after race finishes does not stop

### ISSUE THREAD

**Issue by RnYPT** [MRV6/mp_insidetrack#2] opened 2021-06-07 18:13 UTC
So, some times when the race finishes the "ambient sound" does not stop, the sound only drops to like 50% of volume, i tried to add a StopSound(0) in client.lua in like 89 but with no luck, can you try and fix this?

**Comment by RnYPT** [comment] 2021-06-07 18:27
Btw im in this build "+set sv_enforceGameBuild 2189"

**Comment by RnYPT** [comment] 2021-06-07 19:18
https://streamable.com/jlqoyb

**Comment by MRV6** [comment] 2021-06-10 11:41
Hello, thanks for your feedback. I will try to reproduce this bug.

**Comment by MRV6** [comment] 2021-06-10 11:50
Hopefully fixed in https://github.com/MRV6/mp_insidetrack/commit/86d868642d04b9f2d290924eb20a21462eb93695, can you try now ?

**Comment by MRV6** [comment] 2021-06-10 11:56
Hopefully fixed with the last two commits (86d868642d04b9f2d290924eb20a21462eb93695 & 8480fe6ac89d1dfb85ff8eda4b5fe9e37c840bfd), can you try now ?

**Comment by MRV6** [comment] 2021-06-10 13:00
Hopefully fixed, can you try now ?

**Comment by gunsela92** [comment] 2021-06-14 10:16
Still bugging. I tried but after some races, its bugging. And games are duplicating. For example : I integrated removemoney function and if its bugged the money is removing 3 or 4 times. And sounds are duplicating to. (Btw i tried without removemoney function too its not the problem)

**Comment by MRV6** [comment] 2021-06-14 16:35
This time I can't reproduce the bug, it seems definitely fixed. Are you sure that you updated the resource ?

**Comment by gunsela92** [comment] 2021-06-14 18:42
Yeah i downloaded from the beginning but its happening after 10-15 games.

**Comment by MRV6** [comment] 2021-06-14 19:40
« downloaded from the beginning » ?

**Comment by gunsela92** [comment] 2021-06-14 19:45
I mean downloaded the last version. Discarded my modifications of givemoney and removemoney events.

**Comment by MRV6** [comment] 2021-06-15 08:09
That's pretty weird because I can't reproduce this bug anymore, i will continue to try.

**Comment by MRV6** [comment] 2021-06-27 10:49
I still can't reproduce the issue, it seems like that I definitely fixed it the last time. Also the guy who opened the issue didn't even answer so I can't do much.

**Closed as completed by MRV6** 2021-06-27 10:49 UTC
Labels: bug
